### PR TITLE
GDB-5343 Migrate to Jenkins

### PR DESCRIPTION
**Pull request by desislava-hristova-ontotext**

### CODE REVIEW

**Comment by hudson-onto** [comment]
Build failed!

**Comment by hudson-onto** [comment]
Build failed!

**Comment by desislava-hristova-ontotext** [comment]
Jenkins retry build

**Comment by desislava-hristova-ontotext** [comment]
Jenkins retry build

**Review by svilenvelikov — APPROVED** [review]

**Pull request merged**
